### ISSUE TITLE
Heclib 7 writes DSS v6 vs v7 monthly time points inconsistently

### ISSUE THREAD

**Issue by rma-psmorris** [CentralValleyModeling/wrims#40]
The HecLib 7 library DSS file writes are inconsistent between DSS v6 and DSS v7. One saves at the beginning of next monthly time step and the other saves at the end of the current monthly timestep. (EOP vs BOP?)

Heclib 7 should write out times using the same standard, EOP?

**Comment by rma-psmorris** [comment]
@hxiedwr Which time is the correct one to use?  Beginning of next timestep or the end of the current timestep?

**Comment by hxiedwr** [comment]
We would like to write at EOP.

For example, the current time step is Oct 1921. EOP writes to Oct 31, 1921 2400 but BOP writes to Nov 1, 1921 0000.

EOP represent the right time step but not BOP. I believe EOP is 7 and BOP is 6.

In 6, I do some calculation to change the time stamp.

Thank you,


Hao



________________________________
From: Peter Morris ***@***.***>
Sent: Thursday, January 18, 2024 3:55 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CentralValleyModeling/wrims] Heclib 7 writes DSS v6 vs v7 monthly time points inconsistently (Issue #40)


The HecLib 7 library DSS file writes are inconsistent between DSS v6 and DSS v7. One saves at the beginning of next monthly time step and the other saves at the end of the current monthly timestep. (EOP vs BOP?)

Heclib 7 should write out times using the same standard, EOP?

**Comment by adamkorynta** [comment]
Also to clarify, this is using the HecDss7 branch version of heclib? Using the UI control for 6 is writing differently than when the UI control is switched to 7?

**Comment by hxiedwr** [comment]
When I developed WRIMS 2 by using HecLib 6, I noticed BOP dss data store and read. So I developed code to shift one time step to have the right time stamp.

When I developed WRIMS 2 by using HecLib 7, I noticed EOP dss data store and read in version 7 format. So I modified the code for the one time step data shifting.

When I worked on WRIMS 2 to output dss in version 6 format by using HecLib 7, the same code just hit errors when data store.

I think it must be the EOP and BOP issue because the code in WRIMS 2 are the same. The only difference is the flag switch to write dss data in version 6 or version 7 by using HecLib 7.

Thank you,


Hao



________________________________

**Comment by hxiedwr** [comment]
What I suspected may not be right. It seems not a EOP and BOP issue.

The error I got is when WRIMS 2 writes initial data (obtained from init dss file) to dv dss file. The same code works for HecLib 7 output version 7 format data but not for HecLib 7 output version 6 format.

The exception is as follows:

java.lang.ArrayIndexOutOfBoundsException: 1
      at hec.heclib.dss.HecTimeSeries.setData(HecTimeSeries.java:951)
      at hec.heclib.dss.HecTimeSeries.write(HecTimeSeries.java:1250)
      at hec.heclib.dss.CombinedDataManager.writeData(CombinedDataManager.java:1920)
      at hec.heclib.dss.HecDss.put(HecDss.java:359)
      at wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(DssOperation.java:339)
      at wrimsv2.components.ControllerBatch.runModelCbc(ControllerBatch.java:1725)
      at wrimsv2.components.ControllerBatch.runModel(ControllerBatch.java:268)
      at wrimsv2.components.ControllerBatch.<init>(ControllerBatch.java:102)
      at wrimsv2.components.ControllerBatch.main(ControllerBatch.java:498)
java.lang.ArrayIndexOutOfBoundsException: 12
      at hec.heclib.dss.HecTimeSeries.setData(HecTimeSeries.java:951)
      at hec.heclib.dss.HecTimeSeries.write(HecTimeSeries.java:1250)
      at hec.heclib.dss.CombinedDataManager.writeData(CombinedDataManager.java:1920)
      at hec.heclib.dss.HecDss.put(HecDss.java:359)
      at wrimsv2.evaluator.DssOperation.writeInitDvarAliasToDSS(DssOperation.java:339)
      at wrimsv2.components.ControllerBatch.runModelCbc(ControllerBatch.java:1725)
      at wrimsv2.components.ControllerBatch.runModel(ControllerBatch.java:268)
      at wrimsv2.components.ControllerBatch.<init>(ControllerBatch.java:102)
      at wrimsv2.components.ControllerBatch.main(ControllerBatch.java:498)

Hao
